s="0123456789"
print(s * 2)
print(s[4] * 2)
print("India" == "india")
print("India" > "india")
print("a" > "aa")
print("a" > "a1")
print(s[-2])
print(s[-5:-1])
print(">>", s[-1:4], "<<")
print(len(s))
